name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank's for letting us know... We'll check this out ASAP... congrats on your first issue with us... :)"
        pr-message: "We'll Check this out and let you know if your feature is joining the CareerCompass project... :)"
